/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistLineConfig: typeof import('./src/components/configs/AssistLineConfig.vue')['default']
    CarouselConfig: typeof import('./src/components/configs/CarouselConfig.vue')['default']
    ComGroup: typeof import('./src/components/basic/ComGroup.vue')['default']
    ComRadioGroup: typeof import('./src/components/basic/ComRadioGroup.vue')['default']
    CubeSelectionConfig: typeof import('./src/components/configs/CubeSelectionConfig.vue')['default']
    DialogConfig: typeof import('./src/components/configs/DialogConfig.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FallbackComponent: typeof import('./src/components/FallbackComponent.vue')['default']
    FloatLayerConfig: typeof import('./src/components/configs/FloatLayerConfig.vue')['default']
    ImageNavConfig: typeof import('./src/components/configs/ImageNavConfig.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    NoticeConfig: typeof import('./src/components/configs/NoticeConfig.vue')['default']
    OnlineServiceConfig: typeof import('./src/components/configs/OnlineServiceConfig.vue')['default']
    PreviewIframe: typeof import('./src/components/PreviewIframe.vue')['default']
    ProductConfig: typeof import('./src/components/configs/ProductConfig.vue')['default']
    RichTextConfig: typeof import('./src/components/configs/RichTextConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderConfig: typeof import('./src/components/configs/SliderConfig.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
